import { jsPDF } from "jspdf";
import { GeneratedExam } from "../types";

/**
 * Generates and downloads a clean, beautifully formatted academic PDF of the practice exam.
 */
export function exportExamToPDF(exam: GeneratedExam, includeAnswerKey: boolean = false) {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const maxLineWidth = pageWidth - margin * 2;
  
  let currentY = 25;

  // Helper: Text wrap and print
  function printText(text: string, fontSize: number, style: "normal" | "bold" | "italic" = "normal", spacing: number = 6) {
    doc.setFont("helvetica", style);
    doc.setFontSize(fontSize);
    
    // Split text into lines that fit the page width
    const lines = doc.splitTextToSize(text, maxLineWidth);
    
    lines.forEach((line: string) => {
      if (currentY > pageHeight - 20) {
        doc.addPage();
        drawFooter();
        currentY = 25;
      }
      doc.text(line, margin, currentY);
      currentY += spacing;
    });
  }

  // Draw header/footer decoration
  function drawFooter() {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(8);
    doc.setTextColor(120, 120, 120);
    doc.text(`Exam Page - Generated by NotebookLM Exam Buddy`, margin, pageHeight - 10);
    // Draw horizontal rule
    doc.setDrawColor(220, 220, 220);
    doc.line(margin, pageHeight - 13, pageWidth - margin, pageHeight - 13);
  }

  // Draw initial footer
  drawFooter();

  // Document Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(33, 43, 54);
  doc.text(exam.title, margin, currentY);
  currentY += 10;

  // Metadata Subheader
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(100, 110, 120);
  doc.text(`Format: ${exam.format === "mixed" ? "Mixed Format" : exam.format === "multiple-choice" ? "Multiple Choice" : "Short Answer"}   |   Difficulty: ${exam.difficulty}   |   Questions: ${exam.questionsCount}`, margin, currentY);
  currentY += 6;
  doc.text(`Created: ${new Date(exam.createdDate).toLocaleDateString()}   |   Academic Practice Exam`, margin, currentY);
  currentY += 8;

  // Horizontal separator
  doc.setDrawColor(33, 43, 54);
  doc.setLineWidth(0.5);
  doc.line(margin, currentY, pageWidth - margin, currentY);
  currentY += 12;

  // Instructions
  printText("TEST INSTRUCTIONS", 12, "bold", 6);
  printText(exam.instructions, 10, "normal", 5);
  currentY += 8;

  // Divider
  doc.setDrawColor(230, 230, 230);
  doc.setLineWidth(0.2);
  doc.line(margin, currentY, pageWidth - margin, currentY);
  currentY += 10;

  // Loop Questions
  exam.questions.forEach((q, index) => {
    // Spacer / page check
    if (currentY > pageHeight - 40) {
      doc.addPage();
      drawFooter();
      currentY = 25;
    }

    // Question title
    printText(`Question ${index + 1} (${q.points} pts)`, 11, "bold", 6);
    
    // Question Text
    printText(q.questionText, 10, "normal", 5.5);
    currentY += 2;

    // Options for Multiple Choice
    if (q.type === "multiple-choice" && q.options && q.options.length > 0) {
      q.options.forEach((opt, oIdx) => {
        const prefix = String.fromCharCode(65 + oIdx); // A, B, C, D
        printText(`  [  ]  ${prefix}. ${opt}`, 10, "normal", 5.5);
      });
      currentY += 4;
    } else if (q.type === "short-answer" || q.type === "essay") {
      // Draw lines / write blank lines for students to write answer
      const linesCount = q.type === "short-answer" ? 3 : 6;
      printText("Answer Space:", 9, "italic", 4);
      for (let i = 0; i < linesCount; i++) {
        if (currentY > pageHeight - 15) {
          doc.addPage();
          drawFooter();
          currentY = 25;
        }
        doc.setDrawColor(220, 220, 220);
        doc.line(margin + 5, currentY, pageWidth - margin - 5, currentY);
        currentY += 7;
      }
      currentY += 4;
    }

    currentY += 4;
  });

  // Answer Key Section
  if (includeAnswerKey) {
    doc.addPage();
    drawFooter();
    currentY = 25;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.setTextColor(33, 43, 54);
    doc.text("ANSWER KEY & METHODOLOGY", margin, currentY);
    currentY += 12;

    exam.questions.forEach((q, index) => {
      if (currentY > pageHeight - 35) {
        doc.addPage();
        drawFooter();
        currentY = 25;
      }

      printText(`Question ${index + 1} Solution`, 11, "bold", 6);
      printText(`Correct Answer: ${q.correctAnswer}`, 10, "bold", 5.5);
      printText(`Explanation: ${q.explanation}`, 10, "italic", 5.5);
      currentY += 6;
    });
  }

  // Save PDF
  const sanitizedTitle = exam.title.toLowerCase().replace(/[^a-z0-9]+/g, "_");
  doc.save(`${sanitizedTitle}_exam.pdf`);
}
